FROM ballerina/ballerina

#use this ver for openshift online tool
# COPY test-sl-ver/main.bal /home/ballerina
# COPY test-sl-ver/Ballerina.toml /home/ballerina

#use this version for building an image locally
COPY main.bal /home/ballerina
COPY Ballerina.toml /home/ballerina

RUN bal build
RUN bal run